In [24]:
import torch
from discriminator import Discriminator, DiscriminatorConfig
torch.manual_seed(1337)

a = torch.ones (1, 3, 256, 256)

disc = Discriminator (DiscriminatorConfig)


disc_optimizer = torch.optim.AdamW (disc.parameters(), lr= 6e-4, betas=(0.9,0.95), eps=1e-8)
disc_optimizer.zero_grad()


loss = torch.mean(disc (a))
loss.backward(retain_graph=True)

In [25]:
param_dict = {pn:p for pn,p in disc.named_parameters()}

current_gradients = [param.grad.clone() if param.grad is not None else None for param in disc.parameters()]

In [26]:
for pn, p in disc.named_parameters():
    assert p.grad is not None

In [27]:
for k in param_dict.keys():
    print (k)

in_conv.weight
in_conv.bias
model.1.weight
model.1.bias
model.2.group_norm.weight
model.2.group_norm.bias
model.4.weight
model.4.bias
model.5.group_norm.weight
model.5.group_norm.bias
model.7.weight
model.7.bias
model.8.group_norm.weight
model.8.group_norm.bias
model.10.weight
model.10.bias


In [28]:
disc_optimizer.zero_grad()

In [29]:
print(param_dict["in_conv.weight"].grad)
print (current_gradients[0])

None
tensor([[[[ 0.0595,  0.0609,  0.0609,  0.0607],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0564,  0.0578,  0.0578,  0.0575]],

         [[ 0.0595,  0.0609,  0.0609,  0.0607],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0564,  0.0578,  0.0578,  0.0575]],

         [[ 0.0595,  0.0609,  0.0609,  0.0607],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0564,  0.0578,  0.0578,  0.0575]]],


        [[[-0.1191, -0.1172, -0.1172, -0.1172],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1159, -0.1140, -0.1140, -0.1140]],

         [[-0.1191, -0.1172, -0.1172, -0.1172],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1159, -0.1140, -0.1140, -0.1140]],

         [[-0.1191, -0.

In [30]:
for param, grad_copy in zip (disc.parameters(), current_gradients):
    if grad_copy is not None:
        param.grad = grad_copy.clone()
    else :
        param.grad = None


In [31]:
param_dict["in_conv.weight"].grad.allclose (current_gradients[0])

True

In [32]:
print(param_dict["in_conv.weight"].grad), current_gradients[0]

tensor([[[[ 0.0595,  0.0609,  0.0609,  0.0607],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0564,  0.0578,  0.0578,  0.0575]],

         [[ 0.0595,  0.0609,  0.0609,  0.0607],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0564,  0.0578,  0.0578,  0.0575]],

         [[ 0.0595,  0.0609,  0.0609,  0.0607],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0564,  0.0578,  0.0578,  0.0575]]],


        [[[-0.1191, -0.1172, -0.1172, -0.1172],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1159, -0.1140, -0.1140, -0.1140]],

         [[-0.1191, -0.1172, -0.1172, -0.1172],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1159, -0.1140, -0.1140, -0.1140]],

         [[-0.1191, -0.1172,

(None,
 tensor([[[[ 0.0595,  0.0609,  0.0609,  0.0607],
           [ 0.0590,  0.0604,  0.0604,  0.0601],
           [ 0.0590,  0.0604,  0.0604,  0.0601],
           [ 0.0564,  0.0578,  0.0578,  0.0575]],
 
          [[ 0.0595,  0.0609,  0.0609,  0.0607],
           [ 0.0590,  0.0604,  0.0604,  0.0601],
           [ 0.0590,  0.0604,  0.0604,  0.0601],
           [ 0.0564,  0.0578,  0.0578,  0.0575]],
 
          [[ 0.0595,  0.0609,  0.0609,  0.0607],
           [ 0.0590,  0.0604,  0.0604,  0.0601],
           [ 0.0590,  0.0604,  0.0604,  0.0601],
           [ 0.0564,  0.0578,  0.0578,  0.0575]]],
 
 
         [[[-0.1191, -0.1172, -0.1172, -0.1172],
           [-0.1182, -0.1164, -0.1164, -0.1163],
           [-0.1182, -0.1164, -0.1164, -0.1163],
           [-0.1159, -0.1140, -0.1140, -0.1140]],
 
          [[-0.1191, -0.1172, -0.1172, -0.1172],
           [-0.1182, -0.1164, -0.1164, -0.1163],
           [-0.1182, -0.1164, -0.1164, -0.1163],
           [-0.1159, -0.1140, -0.1140, -0.1140]

In [33]:
micro_step = 1

In [37]:
a = [p for p in disc.parameters()]
b = torch.tensor([a.grad for a in a])

ValueError: only one element tensors can be converted to Python scalars

In [36]:
current_gradients.shape
print 

AttributeError: 'list' object has no attribute 'shape'

In [34]:
for param in disc.parameters ():
    if micro_step == 0:
        current_gradients = [param.grad.clone() if param.grad is not None else None for param in disc.parameters()]
    else:

        current_gradients = [grad + param_grad for grad, param_grad in zip (current_gradients, param.grad)]


RuntimeError: The size of tensor a (64) must match the size of tensor b (4) at non-singleton dimension 2

In [16]:
import torch
from discriminator import Discriminator, DiscriminatorConfig
torch.manual_seed(1337)

a = torch.ones (1, 3, 256, 256)

disc = Discriminator (DiscriminatorConfig)


disc_optimizer = torch.optim.AdamW (disc.parameters(), lr= 6e-4, betas=(0.9,0.95), eps=1e-8)
disc_optimizer.zero_grad()


loss = torch.mean(disc (a))
loss.backward(retain_graph=True)

In [17]:
# vqgan.zero
# vqganbackward
# disc.zero
# dlossbackward
# safe <- clone
# safe += 
reference = [p.grad.clone() for p in disc.parameters()]

In [18]:
for step in range (2):
    if step == 0:
        safe_grad = [p.grad.clone() for p in (disc.parameters())]
    else:
        for i, p in enumerate (disc.parameters()):
            safe_grad[i] += p.grad

In [19]:
for i in range(len(reference)):
    print(reference[i].allclose(0.5 * safe_grad[i]))

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [20]:
for i, p in (enumerate(disc.parameters())):
    p.grad = safe_grad[i]

In [21]:
param_dict = {pn:p for pn,p in disc.named_parameters()}
for k in param_dict.keys():
    print (k)

in_conv.weight
in_conv.bias
model.1.weight
model.1.bias
model.2.group_norm.weight
model.2.group_norm.bias
model.4.weight
model.4.bias
model.5.group_norm.weight
model.5.group_norm.bias
model.7.weight
model.7.bias
model.8.group_norm.weight
model.8.group_norm.bias
model.10.weight
model.10.bias


In [22]:
param_dict["in_conv.weight"].grad

tensor([[[[ 0.1190,  0.1218,  0.1218,  0.1214],
          [ 0.1179,  0.1207,  0.1207,  0.1203],
          [ 0.1179,  0.1207,  0.1207,  0.1203],
          [ 0.1127,  0.1155,  0.1155,  0.1151]],

         [[ 0.1190,  0.1218,  0.1218,  0.1214],
          [ 0.1179,  0.1207,  0.1207,  0.1203],
          [ 0.1179,  0.1207,  0.1207,  0.1203],
          [ 0.1127,  0.1155,  0.1155,  0.1151]],

         [[ 0.1190,  0.1218,  0.1218,  0.1214],
          [ 0.1179,  0.1207,  0.1207,  0.1203],
          [ 0.1179,  0.1207,  0.1207,  0.1203],
          [ 0.1127,  0.1155,  0.1155,  0.1151]]],


        [[[-0.2383, -0.2345, -0.2345, -0.2344],
          [-0.2365, -0.2328, -0.2328, -0.2327],
          [-0.2365, -0.2328, -0.2328, -0.2327],
          [-0.2318, -0.2281, -0.2281, -0.2281]],

         [[-0.2383, -0.2345, -0.2345, -0.2344],
          [-0.2365, -0.2328, -0.2328, -0.2327],
          [-0.2365, -0.2328, -0.2328, -0.2327],
          [-0.2318, -0.2281, -0.2281, -0.2281]],

         [[-0.2383, -0.2345,

In [23]:
print(reference[0].allclose(0.5 * param_dict["in_conv.weight"].grad))

True


In [6]:
a = torch.randn (1,2)
torch.mean(a).type()

'torch.FloatTensor'

In [2]:
from vqgan import VQGan
from encoder import EncoderConfig
from decoder import DecoderConfig
from quantizer import QuantizerConfig
import torch.nn.functional as F
from lpips import LPIPS
from discriminator import Discriminator, DiscriminatorConfig
import torch
import torch.nn.functional as F
disc = Discriminator (DiscriminatorConfig)
disc.to('cuda')
master_process = True
steps_per_epoch = 500
current_step = 501
d_loss_factor = 1.0
perceptual_distinguisher = LPIPS().eval()
def compute_loss (vqgan_model, discriminator, perceptual_distinguisher, x, perceptual_loss_factor, rec_loss_factor, current_step):
    reconstructed_iamges, encoding_indices, vq_loss = vqgan_model (x)
                    
    # Discriminator Forward
    disc_real = discriminator (x)
    disc_generated = discriminator (reconstructed_iamges)
                    
    # VGG forward
    perceptual_loss = perceptual_distinguisher (x, reconstructed_iamges) # (B, 1, 1, 1)
    perceptual_loss = perceptual_loss.squeeze ( ) #(B)
    # formality none of the optimizers have access to vgg params but this way its explicit and efficient
    perceptual_loss = perceptual_loss.detach ( )

    reconstruction_loss = F.mse_loss (x, reconstructed_iamges, reduction='none') #(B, C, H, W)
    reconstruction_loss = reconstruction_loss.mean (dim=(1,2,3)) #(B)

    perceptual_recon_loss = rec_loss_factor * reconstruction_loss + perceptual_loss_factor * perceptual_loss
    perceptual_recon_loss = perceptual_recon_loss.mean()
                    

    # compute adversarial loss for generator if it's not zeroth epoch (VQGAN paper specs)
    is_zeroth_epoch = True if current_step < steps_per_epoch else False
    if is_zeroth_epoch:
        # don't calculate
        # Wasserstein loss, approximation of BCE (discriminator(generated), ones_like(generated))
        # TODO: Internalize throughly
        # good approximation of KLD between discriminator's predictions given generated inputs and ideal distribution of generated images being classified as real.
        # basically mean negative log likelihood is approximation of F.cross_entropy (discriminator(generated), ones_like(generated)) which is approximation of 
        # KLD between (discriminator(generated), ones_like(generated)) which is proportional to
        # BCE (discriminator(genrated), ones_like(generated))
        g_loss = 0 # replace by formula
    else:
        #calculate adversarial loss for generator
        g_loss = - torch.mean (disc_generated)
        lambda_factor = vqgan_model.compute_lambda (perceptual_recon_loss, g_loss)
        g_loss = lambda_factor * g_loss
        if master_process:
            print (f"\nGanLoss{g_loss:.6f} activated!\n")
    
    # VQ GAN LOSS
    # Net Generator Loss
    vq_gan_loss = perceptual_recon_loss + vq_loss + g_loss
                    
    # Discriminator Loss : Hinge Loss. Push Logits for the catgeorical distribution that come out of discriminator 
    # to be more than +1 for real images
    # At the same time Push logits for categorical distribution that comes out of discriminator to be less than -1 for fake images

    # drive logits corresponding to real images from discriminator above zero
    # don't need to explicitly squeeze out the spurious depth dimension (1 channels) from discriminator output, mean will still be evaluated correctly
    d_loss_real= torch.mean(F.relu (1.0 - disc_real))
    # drive logits corresponding to fake(generate) images from discriminator below -1
    d_loss_fake = torch.mean(F.relu (1.0 + disc_generated))

    d_loss = d_loss_factor * 0.5 * (d_loss_real + d_loss_fake)
    return vq_gan_loss, d_loss

model = VQGan (EncoderConfig, QuantizerConfig, DecoderConfig)
model.to('cuda')
perceptual_distinguisher.to('cuda')
vqganloss, d_loss = compute_loss (model, disc, perceptual_distinguisher=perceptual_distinguisher, x=torch.randn(4, 3, 256,256).to('cuda'), perceptual_loss_factor=1.0, rec_loss_factor=1.0, current_step=current_step)


c:\Users\Zen\miniconda3\envs\tr\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\Zen\miniconda3\envs\tr\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
e:\Research\vincentVanGogh\lpips.py:61: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-mod


GanLoss0.051897 activated!



In [3]:
vqganloss.detach()
d_loss.detach()
d_loss.backward(retain_graph=True)
vqganloss.backward (retain_graph=True)

In [4]:
for p in disc.parameters():
    print (p.grad)

tensor([[[[ 2.3016e-06,  2.2884e-04, -1.4995e-03, -6.0753e-04],
          [-6.3334e-04, -1.1158e-03, -2.8435e-04,  4.1176e-04],
          [-1.5370e-03,  3.3530e-04, -7.3614e-04, -8.0269e-04],
          [-3.6014e-04,  7.0143e-04, -7.2644e-04, -5.3296e-04]],

         [[ 1.3175e-03,  2.5511e-03,  2.0090e-03,  4.5501e-03],
          [ 1.5866e-03,  2.1884e-03, -6.9184e-04,  1.3198e-03],
          [ 3.7363e-03,  2.2526e-03,  1.2240e-03,  3.0041e-03],
          [ 7.9151e-04,  9.5182e-04,  1.2971e-03,  2.1345e-03]],

         [[-9.2921e-04, -1.9375e-03,  1.5056e-03,  1.9521e-03],
          [ 4.9500e-04,  7.7120e-04,  2.3979e-03,  1.2511e-04],
          [ 2.8184e-03,  2.6588e-03,  3.7132e-04,  1.3734e-03],
          [-7.4743e-04,  1.4717e-04,  3.4200e-03,  3.1777e-03]]],


        [[[-3.3184e-04, -4.2605e-04,  1.3358e-04, -2.2779e-03],
          [ 8.8769e-04,  1.2908e-03,  9.9415e-05,  1.4471e-04],
          [-3.9182e-04,  8.2815e-04,  2.2906e-04, -8.6381e-04],
          [-4.7981e-05,  1.4979e

In [12]:
cloned_grads = [p.grad.clone() for p in disc.parameters()]
reference = [p.grad.clone() for p in disc.parameters()]
for big_step in range(3):
    cloned_grads = [grad.clone() for grad in reference]
    print (cloned_grads[0].allclose(reference[0]))
    for i in range(2):
        for i,p in enumerate(disc.parameters()):
            cloned_grads[i] += p.grad
        print (cloned_grads[0].allclose(reference[0]))

True
False
False
True
False
False
True
False
False


In [17]:
print (f"ASDSDASD"
       f"asdasdasd")

ASDSDASDasdasdasd


In [18]:
do = True
if do:
    print ("yo")
else:
    print ("no")

print ("aaaa")

yo
aaaa


In [1]:
for _ in range (0):
    print("a")

In [3]:
for nuts in range (1):
    print("a")

a


In [5]:
import torch

In [8]:
a = torch.randn (2048, 1, 512).to('cuda')
b = torch.randn (1024, 512).to('cuda')

c = (a - b).pow(2).mean(2)
c.shape

torch.Size([2048, 1024])