In [24]:
import torch
from discriminator import Discriminator, DiscriminatorConfig
torch.manual_seed(1337)

a = torch.ones (1, 3, 256, 256)

disc = Discriminator (DiscriminatorConfig)


disc_optimizer = torch.optim.AdamW (disc.parameters(), lr= 6e-4, betas=(0.9,0.95), eps=1e-8)
disc_optimizer.zero_grad()


loss = torch.mean(disc (a))
loss.backward(retain_graph=True)

In [25]:
param_dict = {pn:p for pn,p in disc.named_parameters()}

current_gradients = [param.grad.clone() if param.grad is not None else None for param in disc.parameters()]

In [26]:
for pn, p in disc.named_parameters():
    assert p.grad is not None

In [27]:
for k in param_dict.keys():
    print (k)

in_conv.weight
in_conv.bias
model.1.weight
model.1.bias
model.2.group_norm.weight
model.2.group_norm.bias
model.4.weight
model.4.bias
model.5.group_norm.weight
model.5.group_norm.bias
model.7.weight
model.7.bias
model.8.group_norm.weight
model.8.group_norm.bias
model.10.weight
model.10.bias


In [28]:
disc_optimizer.zero_grad()

In [29]:
print(param_dict["in_conv.weight"].grad)
print (current_gradients[0])

None
tensor([[[[ 0.0595,  0.0609,  0.0609,  0.0607],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0564,  0.0578,  0.0578,  0.0575]],

         [[ 0.0595,  0.0609,  0.0609,  0.0607],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0564,  0.0578,  0.0578,  0.0575]],

         [[ 0.0595,  0.0609,  0.0609,  0.0607],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0564,  0.0578,  0.0578,  0.0575]]],


        [[[-0.1191, -0.1172, -0.1172, -0.1172],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1159, -0.1140, -0.1140, -0.1140]],

         [[-0.1191, -0.1172, -0.1172, -0.1172],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1159, -0.1140, -0.1140, -0.1140]],

         [[-0.1191, -0.

In [30]:
for param, grad_copy in zip (disc.parameters(), current_gradients):
    if grad_copy is not None:
        param.grad = grad_copy.clone()
    else :
        param.grad = None


In [31]:
param_dict["in_conv.weight"].grad.allclose (current_gradients[0])

True

In [32]:
print(param_dict["in_conv.weight"].grad), current_gradients[0]

tensor([[[[ 0.0595,  0.0609,  0.0609,  0.0607],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0564,  0.0578,  0.0578,  0.0575]],

         [[ 0.0595,  0.0609,  0.0609,  0.0607],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0564,  0.0578,  0.0578,  0.0575]],

         [[ 0.0595,  0.0609,  0.0609,  0.0607],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0590,  0.0604,  0.0604,  0.0601],
          [ 0.0564,  0.0578,  0.0578,  0.0575]]],


        [[[-0.1191, -0.1172, -0.1172, -0.1172],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1159, -0.1140, -0.1140, -0.1140]],

         [[-0.1191, -0.1172, -0.1172, -0.1172],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1182, -0.1164, -0.1164, -0.1163],
          [-0.1159, -0.1140, -0.1140, -0.1140]],

         [[-0.1191, -0.1172,

(None,
 tensor([[[[ 0.0595,  0.0609,  0.0609,  0.0607],
           [ 0.0590,  0.0604,  0.0604,  0.0601],
           [ 0.0590,  0.0604,  0.0604,  0.0601],
           [ 0.0564,  0.0578,  0.0578,  0.0575]],
 
          [[ 0.0595,  0.0609,  0.0609,  0.0607],
           [ 0.0590,  0.0604,  0.0604,  0.0601],
           [ 0.0590,  0.0604,  0.0604,  0.0601],
           [ 0.0564,  0.0578,  0.0578,  0.0575]],
 
          [[ 0.0595,  0.0609,  0.0609,  0.0607],
           [ 0.0590,  0.0604,  0.0604,  0.0601],
           [ 0.0590,  0.0604,  0.0604,  0.0601],
           [ 0.0564,  0.0578,  0.0578,  0.0575]]],
 
 
         [[[-0.1191, -0.1172, -0.1172, -0.1172],
           [-0.1182, -0.1164, -0.1164, -0.1163],
           [-0.1182, -0.1164, -0.1164, -0.1163],
           [-0.1159, -0.1140, -0.1140, -0.1140]],
 
          [[-0.1191, -0.1172, -0.1172, -0.1172],
           [-0.1182, -0.1164, -0.1164, -0.1163],
           [-0.1182, -0.1164, -0.1164, -0.1163],
           [-0.1159, -0.1140, -0.1140, -0.1140]

In [33]:
micro_step = 1

In [37]:
a = [p for p in disc.parameters()]
b = torch.tensor([a.grad for a in a])

ValueError: only one element tensors can be converted to Python scalars

In [36]:
current_gradients.shape
print 

AttributeError: 'list' object has no attribute 'shape'

In [34]:
for param in disc.parameters ():
    if micro_step == 0:
        current_gradients = [param.grad.clone() if param.grad is not None else None for param in disc.parameters()]
    else:

        current_gradients = [grad + param_grad for grad, param_grad in zip (current_gradients, param.grad)]


RuntimeError: The size of tensor a (64) must match the size of tensor b (4) at non-singleton dimension 2

In [54]:
import torch
from discriminator import Discriminator, DiscriminatorConfig
torch.manual_seed(1337)

a = torch.ones (1, 3, 256, 256)

disc = Discriminator (DiscriminatorConfig)


disc_optimizer = torch.optim.AdamW (disc.parameters(), lr= 6e-4, betas=(0.9,0.95), eps=1e-8)
disc_optimizer.zero_grad()


loss = torch.mean(disc (a))
loss.backward(retain_graph=True)

In [55]:
# vqgan.zero
# vqganbackward
# disc.zero
# dlossbackward
# safe <- clone
# safe += 
reference = [p.grad.clone() for p in disc.parameters()]

In [56]:
for step in range (2):
    if step == 0:
        safe_grad = [p.grad.clone() for i,p in enumerate(disc.parameters())]
    else:
        for i, p in enumerate (disc.parameters()):
            safe_grad[i] += p.grad

In [57]:
for i in range(len(reference)):
    print(reference[i].allclose(0.5 * safe_grad[i]))

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [60]:
for i, p in (enumerate(disc.parameters())):
    p.grad = safe_grad[i].clone()

In [63]:
param_dict = {pn:p for pn,p in disc.named_parameters()}
for k in param_dict.keys():
    print (k)

in_conv.weight
in_conv.bias
model.1.weight
model.1.bias
model.2.group_norm.weight
model.2.group_norm.bias
model.4.weight
model.4.bias
model.5.group_norm.weight
model.5.group_norm.bias
model.7.weight
model.7.bias
model.8.group_norm.weight
model.8.group_norm.bias
model.10.weight
model.10.bias


In [64]:
param_dict["in_conv.weight"].grad

tensor([[[[ 0.1190,  0.1218,  0.1218,  0.1214],
          [ 0.1179,  0.1207,  0.1207,  0.1203],
          [ 0.1179,  0.1207,  0.1207,  0.1203],
          [ 0.1127,  0.1155,  0.1155,  0.1151]],

         [[ 0.1190,  0.1218,  0.1218,  0.1214],
          [ 0.1179,  0.1207,  0.1207,  0.1203],
          [ 0.1179,  0.1207,  0.1207,  0.1203],
          [ 0.1127,  0.1155,  0.1155,  0.1151]],

         [[ 0.1190,  0.1218,  0.1218,  0.1214],
          [ 0.1179,  0.1207,  0.1207,  0.1203],
          [ 0.1179,  0.1207,  0.1207,  0.1203],
          [ 0.1127,  0.1155,  0.1155,  0.1151]]],


        [[[-0.2383, -0.2345, -0.2345, -0.2344],
          [-0.2365, -0.2328, -0.2328, -0.2327],
          [-0.2365, -0.2328, -0.2328, -0.2327],
          [-0.2318, -0.2281, -0.2281, -0.2281]],

         [[-0.2383, -0.2345, -0.2345, -0.2344],
          [-0.2365, -0.2328, -0.2328, -0.2327],
          [-0.2365, -0.2328, -0.2328, -0.2327],
          [-0.2318, -0.2281, -0.2281, -0.2281]],

         [[-0.2383, -0.2345,

In [65]:
print(reference[0].allclose(0.5 * param_dict["in_conv.weight"].grad))

True
